#%RAML 1.0
title: worldtimezone-api
protocols:
  - HTTP
version: v1

/{region}/{city}:
    get:
      description: Get Time Zone
      displayName: GETTIMEZONE
      responses:
        200:
          body:
            application/json:
              example:
                {"abbreviation":"PDT","client_ip":"13.59.19.40","datetime":"2020-07-16T03:23:07.021035-07:00","day_of_week":4,"day_of_year":198,"dst":true,"dst_from":"2020-03-08T10:00:00+00:00","dst_offset":3600,"dst_until":"2020-11-01T09:00:00+00:00","raw_offset":-28800,"timezone":"America/Los_Angeles","unixtime":1594894987,"utc_datetime":"2020-07-16T10:23:07.021035+00:00","utc_offset":"-07:00","week_number":29}

      